"""
Phase 7 — Python Exploratory Data Analysis.

Uses Pandas/NumPy/Matplotlib/Seaborn to explore patterns not obvious from
the Phase 5/6 SQL analytics: distribution shapes, outliers, seasonality,
and bivariate relationships. Reads data/processed/*.csv (Phase 3 output);
writes figures to reports/figures/phase7/ and a stats summary to
reports/phase7_eda_stats.md.

Every number printed/saved here is computed directly from the data — no
manufactured conclusions. Interpretation is written up separately in
docs/phase7_findings.md, referencing these figures and numbers.

Run from the project root:
    python python/eda.py
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as scipy_stats

PROCESSED_DIR = Path(__file__).resolve().parent.parent / "data" / "processed"
FIG_DIR = Path(__file__).resolve().parent.parent / "reports" / "figures" / "phase7"
STATS_PATH = Path(__file__).resolve().parent.parent / "reports" / "phase7_eda_stats.md"

sns.set_theme(style="whitegrid")
plt.rcParams["figure.dpi"] = 110


def load_data():
    sales = pd.read_csv(PROCESSED_DIR / "sales_clean.csv", parse_dates=["Order Date", "Delivery Date"])
    customers = pd.read_csv(PROCESSED_DIR / "customers_clean.csv", parse_dates=["Birthday"])
    products = pd.read_csv(PROCESSED_DIR / "products_clean.csv")
    stores = pd.read_csv(PROCESSED_DIR / "stores_clean.csv")
    return sales, customers, products, stores


def savefig(name):
    path = FIG_DIR / f"{name}.png"
    plt.tight_layout()
    plt.savefig(path, bbox_inches="tight")
    plt.close()
    return path


def main():
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    sales, customers, products, stores = load_data()
    stats_lines = ["# Phase 7 — EDA Computed Statistics\n",
                   "Raw numeric output backing docs/phase7_findings.md. "
                   "Generated by python/eda.py.\n"]

    # ------------------------------------------------------------------
    # 1. UNIVARIATE: Order-level revenue distribution
    # ------------------------------------------------------------------
    order_revenue = sales.groupby("Order Number")["Revenue USD"].sum()

    stats_lines.append("## Order Revenue Distribution\n")
    desc = order_revenue.describe()
    stats_lines.append(f"- Count: {desc['count']:.0f}, Mean: ${desc['mean']:.2f}, Median: ${order_revenue.median():.2f}")
    stats_lines.append(f"- Std Dev: ${desc['std']:.2f}, Min: ${desc['min']:.2f}, Max: ${desc['max']:.2f}")
    skew = scipy_stats.skew(order_revenue)
    stats_lines.append(f"- Skewness: {skew:.3f} ({'right-skewed (long tail of high-value orders)' if skew > 0.5 else 'roughly symmetric'})")

    # IQR-based outlier detection
    q1, q3 = order_revenue.quantile([0.25, 0.75])
    iqr = q3 - q1
    upper_fence = q3 + 1.5 * iqr
    outliers = order_revenue[order_revenue > upper_fence]
    stats_lines.append(f"- IQR outlier fence (Q3 + 1.5×IQR): ${upper_fence:.2f}")
    stats_lines.append(f"- Orders above outlier fence: {len(outliers):,} ({100*len(outliers)/len(order_revenue):.2f}% of orders), "
                        f"contributing ${outliers.sum():,.2f} ({100*outliers.sum()/order_revenue.sum():.2f}% of total revenue)\n")

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    sns.histplot(order_revenue, bins=60, ax=axes[0], color="#4C72B0")
    axes[0].set_title("Order Revenue Distribution")
    axes[0].set_xlabel("Order Revenue (USD)")
    sns.boxplot(x=order_revenue, ax=axes[1], color="#4C72B0")
    axes[1].set_title("Order Revenue — Boxplot (outliers visible)")
    axes[1].set_xlabel("Order Revenue (USD)")
    savefig("01_order_revenue_distribution")

    # ------------------------------------------------------------------
    # 2. UNIVARIATE: Line items per order
    # ------------------------------------------------------------------
    items_per_order = sales.groupby("Order Number").size()
    stats_lines.append("## Line Items per Order\n")
    stats_lines.append(f"- Mean: {items_per_order.mean():.2f}, Median: {items_per_order.median():.0f}, "
                        f"Max: {items_per_order.max()}, Mode: {items_per_order.mode().iloc[0]}\n")

    plt.figure(figsize=(7, 4.5))
    sns.countplot(x=items_per_order, color="#55A868")
    plt.title("Line Items per Order")
    plt.xlabel("Number of Line Items")
    plt.ylabel("Number of Orders")
    savefig("02_line_items_per_order")

    # ------------------------------------------------------------------
    # 3. Customer spending distribution
    # ------------------------------------------------------------------
    customer_revenue = sales.groupby("CustomerKey")["Revenue USD"].sum()
    stats_lines.append("## Customer Total Spend Distribution (purchasing customers only)\n")
    cdesc = customer_revenue.describe()
    stats_lines.append(f"- Count: {cdesc['count']:.0f}, Mean: ${cdesc['mean']:.2f}, Median: ${customer_revenue.median():.2f}")
    stats_lines.append(f"- Std Dev: ${cdesc['std']:.2f}, Min: ${cdesc['min']:.2f}, Max: ${cdesc['max']:.2f}")
    cskew = scipy_stats.skew(customer_revenue)
    stats_lines.append(f"- Skewness: {cskew:.3f}\n")

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    sns.histplot(customer_revenue, bins=60, ax=axes[0], color="#C44E52")
    axes[0].set_title("Customer Total Spend (linear scale)")
    axes[0].set_xlabel("Total Spend (USD)")
    sns.histplot(np.log10(customer_revenue), bins=60, ax=axes[1], color="#C44E52")
    axes[1].set_title("Customer Total Spend (log10 scale)")
    axes[1].set_xlabel("log10(Total Spend USD)")
    savefig("03_customer_spend_distribution")

    # ------------------------------------------------------------------
    # 4. BIVARIATE: Quantity vs Revenue at product level (scatter)
    # ------------------------------------------------------------------
    prod_summary = sales.groupby("ProductKey").agg(
        total_quantity=("Quantity", "sum"),
        total_revenue=("Revenue USD", "sum"),
    ).reset_index().merge(products[["ProductKey", "Category"]], on="ProductKey")

    corr = prod_summary["total_quantity"].corr(prod_summary["total_revenue"])
    stats_lines.append("## Product-Level: Quantity Sold vs. Revenue\n")
    stats_lines.append(f"- Pearson correlation (quantity sold vs. revenue), across {len(prod_summary)} products with sales: {corr:.3f}\n")

    plt.figure(figsize=(8, 5.5))
    sns.scatterplot(data=prod_summary, x="total_quantity", y="total_revenue", hue="Category", alpha=0.7, s=35)
    plt.title("Product-Level: Units Sold vs. Revenue")
    plt.xlabel("Total Units Sold")
    plt.ylabel("Total Revenue (USD)")
    plt.legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=8)
    savefig("04_quantity_vs_revenue_by_product")

    # ------------------------------------------------------------------
    # 5. TIME SERIES: monthly revenue + seasonality
    # ------------------------------------------------------------------
    sales["year"] = sales["Order Date"].dt.year
    sales["month"] = sales["Order Date"].dt.month
    sales["month_name"] = sales["Order Date"].dt.month_name()
    sales["weekday"] = sales["Order Date"].dt.day_name()

    monthly = sales.groupby(sales["Order Date"].dt.to_period("M"))["Revenue USD"].sum()
    stats_lines.append("## Time Series\n")
    stats_lines.append(f"- Monthly revenue range: ${monthly.min():,.2f} (min) to ${monthly.max():,.2f} (max)")
    stats_lines.append(f"- Month with highest revenue: {monthly.idxmax()} (${monthly.max():,.2f})")
    stats_lines.append(f"- Month with lowest revenue: {monthly.idxmin()} (${monthly.min():,.2f})\n")

    plt.figure(figsize=(11, 4.5))
    monthly.plot(kind="line", marker="o", markersize=3, color="#4C72B0")
    plt.title("Monthly Revenue Over Time (Note: 2021 is partial — Jan/Feb only)")
    plt.ylabel("Revenue (USD)")
    plt.xlabel("Month")
    savefig("05_monthly_revenue_trend")

    # Seasonality: average revenue by calendar month, excluding partial final year
    full_years = sales[sales["year"] < sales["year"].max()]
    monthly_seasonality = full_years.groupby("month")["Revenue USD"].sum() / full_years["year"].nunique()
    stats_lines.append(f"- Avg monthly revenue by calendar month (full years {full_years['year'].min()}-{full_years['year'].max()} only):")
    for m, v in monthly_seasonality.items():
        stats_lines.append(f"  - Month {m}: ${v:,.2f}")
    stats_lines.append("")

    plt.figure(figsize=(9, 4.5))
    monthly_seasonality.plot(kind="bar", color="#55A868")
    plt.title(f"Avg Revenue by Calendar Month ({full_years['year'].min()}-{full_years['year'].max()}, full years only)")
    plt.xlabel("Month")
    plt.ylabel("Avg Revenue (USD)")
    savefig("06_seasonality_by_month")

    # Weekday pattern
    weekday_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    weekday_rev = sales.groupby("weekday")["Revenue USD"].sum().reindex(weekday_order)
    stats_lines.append("- Revenue by day of week:")
    for d, v in weekday_rev.items():
        stats_lines.append(f"  - {d}: ${v:,.2f}")
    stats_lines.append("")

    plt.figure(figsize=(8, 4.5))
    weekday_rev.plot(kind="bar", color="#8172B2")
    plt.title("Total Revenue by Day of Week")
    plt.ylabel("Revenue (USD)")
    savefig("07_revenue_by_weekday")

    # ------------------------------------------------------------------
    # 6. Category performance (boxplot of order-line revenue by category)
    # ------------------------------------------------------------------
    sales_cat = sales.merge(products[["ProductKey", "Category"]], on="ProductKey")
    plt.figure(figsize=(10, 5.5))
    order_cat = sales_cat.groupby("Category")["Revenue USD"].median().sort_values(ascending=False).index
    sns.boxplot(data=sales_cat, x="Category", y="Revenue USD", order=order_cat, showfliers=False)
    plt.xticks(rotation=40, ha="right")
    plt.title("Line-Item Revenue by Category (outliers hidden for readability)")
    plt.ylabel("Revenue (USD) per line item")
    savefig("08_revenue_by_category_boxplot")

    # ------------------------------------------------------------------
    # 7. Regional: revenue distribution by country (customer-side)
    # ------------------------------------------------------------------
    sales_geo = sales.merge(customers[["CustomerKey", "Country"]], on="CustomerKey")
    plt.figure(figsize=(9, 5))
    country_order = sales_geo.groupby("Country")["Revenue USD"].sum().sort_values(ascending=False).index
    sns.barplot(data=sales_geo.groupby("Country")["Revenue USD"].sum().reset_index(),
                x="Country", y="Revenue USD", order=country_order, color="#4C72B0")
    plt.xticks(rotation=40, ha="right")
    plt.title("Total Revenue by Customer Country")
    plt.ylabel("Revenue (USD)")
    savefig("09_revenue_by_country")

    # ------------------------------------------------------------------
    # 8. Customer age distribution (at time of most recent order in dataset)
    # ------------------------------------------------------------------
    max_date = sales["Order Date"].max()
    cust_with_orders = customers[customers["CustomerKey"].isin(sales["CustomerKey"].unique())].copy()
    cust_with_orders["age_at_dataset_end"] = (
        (max_date - cust_with_orders["Birthday"]).dt.days / 365.25
    )
    stats_lines.append("## Customer Age (purchasing customers, age as of latest order date in dataset)\n")
    adesc = cust_with_orders["age_at_dataset_end"].describe()
    stats_lines.append(f"- Mean age: {adesc['mean']:.1f}, Median: {cust_with_orders['age_at_dataset_end'].median():.1f}, "
                        f"Min: {adesc['min']:.1f}, Max: {adesc['max']:.1f}\n")

    plt.figure(figsize=(8, 4.5))
    sns.histplot(cust_with_orders["age_at_dataset_end"], bins=40, color="#C44E52")
    plt.title("Age Distribution — Purchasing Customers")
    plt.xlabel("Age (years, as of latest order date in dataset)")
    savefig("10_customer_age_distribution")

    # ------------------------------------------------------------------
    # 9. Outlier analysis: extreme single line-item quantities/revenue
    # ------------------------------------------------------------------
    line_revenue = sales["Revenue USD"]
    q1_l, q3_l = line_revenue.quantile([0.25, 0.75])
    iqr_l = q3_l - q1_l
    fence_l = q3_l + 1.5 * iqr_l
    line_outliers = sales[line_revenue > fence_l]
    stats_lines.append("## Line-Item Level Outlier Check\n")
    stats_lines.append(f"- IQR outlier fence (line-item Revenue USD): ${fence_l:.2f}")
    stats_lines.append(f"- Line items above fence: {len(line_outliers):,} ({100*len(line_outliers)/len(sales):.2f}% of all line items)")
    stats_lines.append(f"- These are legitimate high-price/high-quantity product purchases (e.g. desktops, "
                        f"large TVs), not data-entry errors — max single line-item revenue: ${line_revenue.max():,.2f} "
                        f"(Quantity={sales.loc[line_revenue.idxmax(),'Quantity']}, "
                        f"Product={products.loc[products['ProductKey']==sales.loc[line_revenue.idxmax(),'ProductKey'],'Product Name'].values[0]})\n")

    STATS_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATS_PATH.write_text("\n".join(stats_lines), encoding="utf-8")

    print(f"Figures written to {FIG_DIR}")
    print(f"Stats written to {STATS_PATH}")


if __name__ == "__main__":
    main()
