"""
Phase 2 — Dataset Ingestion & Data Understanding.

Loads the raw CSVs from data/raw/ and profiles each table:
- shape, dtypes, missing values, duplicates
- key cardinalities (customers, orders, products, stores)
- date ranges
- categorical value counts (category, country, currency)
- numeric ranges (price, cost, quantity)
- referential integrity checks across tables (foreign keys)

This script does NOT clean or modify any data. It only reads data/raw/ and
writes a profiling report to reports/phase2_data_profiling_report.md.

Run from the project root:
    python python/profile_data.py
"""

from pathlib import Path
from datetime import datetime
import pandas as pd

RAW_DIR = Path(__file__).resolve().parent.parent / "data" / "raw"
REPORT_PATH = Path(__file__).resolve().parent.parent / "reports" / "phase2_data_profiling_report.md"


def load_raw():
    sales = pd.read_csv(RAW_DIR / "Sales.csv", encoding="utf-8")
    customers = pd.read_csv(RAW_DIR / "Customers.csv", encoding="cp1252")
    products = pd.read_csv(RAW_DIR / "Products.csv", encoding="utf-8")
    stores = pd.read_csv(RAW_DIR / "Stores.csv", encoding="utf-8")
    exchange = pd.read_csv(RAW_DIR / "Exchange_Rates.csv", encoding="utf-8")
    data_dict = pd.read_csv(RAW_DIR / "Data_Dictionary.csv", encoding="utf-8")
    return {
        "Sales": sales,
        "Customers": customers,
        "Products": products,
        "Stores": stores,
        "Exchange_Rates": exchange,
        "Data_Dictionary": data_dict,
    }


def basic_profile(name, df, lines):
    lines.append(f"\n## {name}\n")
    lines.append(f"- Rows: **{len(df):,}**")
    lines.append(f"- Columns: **{df.shape[1]}**")
    lines.append(f"- Duplicate rows (all columns identical): **{df.duplicated().sum():,}**")
    lines.append("\n**Columns / dtypes / missing values:**\n")
    lines.append("| Column | Dtype | Missing (n) | Missing (%) |")
    lines.append("|---|---|---|---|")
    for col in df.columns:
        n_missing = df[col].isna().sum()
        pct_missing = round(100 * n_missing / len(df), 2) if len(df) else 0
        lines.append(f"| {col} | {df[col].dtype} | {n_missing:,} | {pct_missing}% |")


def main():
    tables = load_raw()
    lines = []
    lines.append("# Phase 2 — Data Profiling Report")
    lines.append(f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("\nSource: `data/raw/` (unmodified). This report is generated by "
                  "`python/profile_data.py` and reflects the raw files exactly as provided.")

    for name, df in tables.items():
        basic_profile(name, df, lines)

    # ---- Sales-specific profiling ----
    sales = tables["Sales"]
    lines.append("\n## Sales — Business-Relevant Profiling\n")

    lines.append(f"- Unique Order Numbers: **{sales['Order Number'].nunique():,}**")
    lines.append(f"- Unique (Order Number, Line Item) combinations: "
                  f"**{sales.drop_duplicates(['Order Number','Line Item']).shape[0]:,}** "
                  f"(vs {len(sales):,} total rows)")
    lines.append(f"- Unique CustomerKey values in Sales: **{sales['CustomerKey'].nunique():,}**")
    lines.append(f"- Unique ProductKey values in Sales: **{sales['ProductKey'].nunique():,}**")
    lines.append(f"- Unique StoreKey values in Sales: **{sales['StoreKey'].nunique():,}**")
    lines.append(f"- Unique Currency Codes: **{sorted(sales['Currency Code'].dropna().unique().tolist())}**")

    order_dates = pd.to_datetime(sales["Order Date"], format="%m/%d/%Y", errors="coerce")
    lines.append(f"- Order Date range: **{order_dates.min().date()} → {order_dates.max().date()}**")
    lines.append(f"- Order Date unparseable/missing after parsing: **{order_dates.isna().sum():,}**")

    delivery_dates = pd.to_datetime(sales["Delivery Date"], format="%m/%d/%Y", errors="coerce")
    lines.append(f"- Delivery Date missing (blank in source): **{sales['Delivery Date'].isna().sum():,}** "
                  f"({round(100*sales['Delivery Date'].isna().sum()/len(sales),2)}%)")
    lines.append(f"- Delivery Date unparseable (non-blank but invalid): "
                  f"**{(delivery_dates.isna() & sales['Delivery Date'].notna()).sum():,}**")

    lines.append(f"- Quantity — min: **{sales['Quantity'].min()}**, max: **{sales['Quantity'].max()}**, "
                  f"mean: **{round(sales['Quantity'].mean(),2)}**")
    lines.append(f"- Quantity <= 0 (invalid): **{(sales['Quantity'] <= 0).sum():,}**")

    # ---- Products-specific profiling ----
    products = tables["Products"]
    lines.append("\n## Products — Business-Relevant Profiling\n")
    lines.append(f"- Unique ProductKey: **{products['ProductKey'].nunique():,}**")
    lines.append(f"- Unique Categories: **{sorted(products['Category'].dropna().unique().tolist())}**")
    lines.append(f"- Unique Subcategories: **{products['Subcategory'].nunique():,}**")
    lines.append(f"- Unique Brands: **{products['Brand'].nunique():,}**")

    def parse_money(series):
        return pd.to_numeric(
            series.astype(str).str.replace(r"[$,]", "", regex=True).str.strip(),
            errors="coerce"
        )

    unit_cost = parse_money(products["Unit Cost USD"])
    unit_price = parse_money(products["Unit Price USD"])
    lines.append(f"- Unit Cost USD (parsed) — min: **${unit_cost.min():.2f}**, max: **${unit_cost.max():.2f}**, "
                  f"unparseable: **{unit_cost.isna().sum():,}**")
    lines.append(f"- Unit Price USD (parsed) — min: **${unit_price.min():.2f}**, max: **${unit_price.max():.2f}**, "
                  f"unparseable: **{unit_price.isna().sum():,}**")
    lines.append(f"- Rows where Unit Price < Unit Cost (would sell at a loss): "
                  f"**{(unit_price < unit_cost).sum():,}**")

    # ---- Customers-specific profiling ----
    customers = tables["Customers"]
    lines.append("\n## Customers — Business-Relevant Profiling\n")
    lines.append(f"- Unique CustomerKey: **{customers['CustomerKey'].nunique():,}** "
                 f"(vs {len(customers):,} rows — {'no duplicate keys' if customers['CustomerKey'].nunique()==len(customers) else 'DUPLICATE KEYS PRESENT'})")
    lines.append(f"- Unique Countries: **{customers['Country'].nunique():,}**")
    lines.append(f"- Unique Continents: **{sorted(customers['Continent'].dropna().unique().tolist())}**")
    lines.append(f"- Gender value counts: {customers['Gender'].value_counts().to_dict()}")

    # ---- Stores-specific profiling ----
    stores = tables["Stores"]
    lines.append("\n## Stores — Business-Relevant Profiling\n")
    lines.append(f"- Unique StoreKey: **{stores['StoreKey'].nunique():,}** (vs {len(stores):,} rows)")
    lines.append(f"- Unique Countries: **{sorted(stores['Country'].dropna().unique().tolist())}**")
    lines.append(f"- Square Meters — min: **{stores['Square Meters'].min()}**, max: **{stores['Square Meters'].max()}**, "
                  f"missing: **{stores['Square Meters'].isna().sum():,}**")
    # StoreKey 0 often represents "online" in this well-known dataset — check, don't assume
    lines.append(f"- StoreKey values present in Stores.csv: **{sorted(stores['StoreKey'].unique().tolist())[:5]}...{sorted(stores['StoreKey'].unique().tolist())[-3:]}**")

    # ---- Exchange Rates profiling ----
    exch = tables["Exchange_Rates"]
    lines.append("\n## Exchange_Rates — Business-Relevant Profiling\n")
    exch_dates = pd.to_datetime(exch["Date"], format="%m/%d/%Y", errors="coerce")
    lines.append(f"- Date range: **{exch_dates.min().date()} → {exch_dates.max().date()}**")
    lines.append(f"- Currencies covered: **{sorted(exch['Currency'].unique().tolist())}**")

    # ---- Referential integrity checks ----
    lines.append("\n## Referential Integrity Checks\n")

    orphan_customers = sales.loc[~sales["CustomerKey"].isin(customers["CustomerKey"]), "CustomerKey"]
    lines.append(f"- Sales rows with CustomerKey NOT found in Customers.csv: **{orphan_customers.shape[0]:,}** "
                 f"(unique orphan keys: {orphan_customers.nunique():,})")

    orphan_products = sales.loc[~sales["ProductKey"].isin(products["ProductKey"]), "ProductKey"]
    lines.append(f"- Sales rows with ProductKey NOT found in Products.csv: **{orphan_products.shape[0]:,}** "
                 f"(unique orphan keys: {orphan_products.nunique():,})")

    orphan_stores = sales.loc[~sales["StoreKey"].isin(stores["StoreKey"]), "StoreKey"]
    lines.append(f"- Sales rows with StoreKey NOT found in Stores.csv: **{orphan_stores.shape[0]:,}** "
                 f"(unique orphan keys: {sorted(orphan_stores.unique().tolist())})")

    sales_currencies = set(sales["Currency Code"].dropna().unique())
    exch_currencies = set(exch["Currency"].dropna().unique())
    missing_curr = sales_currencies - exch_currencies
    lines.append(f"- Currency codes in Sales.csv not present in Exchange_Rates.csv: **{sorted(missing_curr) if missing_curr else 'None'}**")

    # date coverage check for FX join
    sales_date_range = (order_dates.min(), order_dates.max())
    exch_date_range = (exch_dates.min(), exch_dates.max())
    fx_covers_sales = exch_date_range[0] <= sales_date_range[0] and exch_date_range[1] >= sales_date_range[1]
    lines.append(f"- Exchange_Rates date range fully covers Sales date range: **{fx_covers_sales}**")

    Path(REPORT_PATH).parent.mkdir(parents=True, exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(str(l) for l in lines))

    print(f"Report written to {REPORT_PATH}")


if __name__ == "__main__":
    main()
