"""
Generic SQL analytics runner.

Parses a .sql file for blocks delimited by "-- @query: <name>" markers
(each followed by an optional comment description and then the SQL
statement, terminated by the next marker or end of file), executes each
query against the project's SQLite database, and writes a markdown report
with the query, its business-question comment, and the actual result rows.

Usage:
    python python/run_sql_analytics.py sql/05_sales_analytics.sql "Phase 5 — SQL Sales Analytics" reports/phase5_sales_analytics_report.md
"""

import sys
import re
import sqlite3
from pathlib import Path
import pandas as pd

DB_PATH = Path(__file__).resolve().parent.parent / "data" / "processed" / "ecommerce_analytics.db"


def parse_queries(sql_text: str):
    """Split a .sql file into (name, sql_block) pairs on '-- @query: name' markers."""
    pattern = re.compile(r"--\s*@query:\s*(\S+)\s*\n(.*?)(?=(?:--\s*@query:)|\Z)", re.DOTALL)
    queries = []
    for match in pattern.finditer(sql_text):
        name = match.group(1).strip()
        block = match.group(2).strip()
        # Strip a trailing section-header comment block (e.g. a "-- ====...."
        # banner introducing the *next* section) that got swept in because it
        # precedes the next @query marker.
        block = re.sub(r"\n-- ={10,}.*\Z", "", block, flags=re.DOTALL).strip()
        queries.append((name, block))
    return queries


def main():
    if len(sys.argv) != 4:
        print("Usage: python run_sql_analytics.py <sql_file> <report_title> <output_md>")
        sys.exit(1)

    sql_file = Path(sys.argv[1])
    title = sys.argv[2]
    output_md = Path(sys.argv[3])

    sql_text = sql_file.read_text(encoding="utf-8")
    queries = parse_queries(sql_text)

    conn = sqlite3.connect(DB_PATH)

    lines = [f"# {title}", "", f"Generated by running `{sql_file}` against `{DB_PATH.name}`.", ""]

    for name, block in queries:
        # Separate leading comment lines (business question) from the SQL itself
        comment_lines = []
        sql_lines = []
        for line in block.split("\n"):
            stripped = line.strip()
            if stripped.startswith("--") and not sql_lines:
                comment_lines.append(stripped.lstrip("-").strip())
            else:
                sql_lines.append(line)
        business_question = " ".join(c for c in comment_lines if c)
        sql_stmt = "\n".join(sql_lines).strip()
        if sql_stmt.endswith(";"):
            sql_stmt = sql_stmt[:-1]

        lines.append(f"## {name}")
        if business_question:
            lines.append(f"\n*{business_question}*\n")
        lines.append("```sql")
        lines.append(sql_stmt + ";")
        lines.append("```\n")

        try:
            df = pd.read_sql_query(sql_stmt, conn)
            if len(df) == 0:
                lines.append("_No rows returned._\n")
            else:
                df_fmt = df.copy()
                for col in df_fmt.columns:
                    if col.lower() in ("year", "quarter", "month", "rank"):
                        continue  # don't thousands-separate identifier-like integers
                    if pd.api.types.is_float_dtype(df_fmt[col]):
                        df_fmt[col] = df_fmt[col].map(
                            lambda x: f"{x:,.2f}" if pd.notna(x) else ""
                        )
                    elif pd.api.types.is_integer_dtype(df_fmt[col]):
                        df_fmt[col] = df_fmt[col].map(lambda x: f"{x:,}" if pd.notna(x) else "")
                lines.append(df_fmt.to_markdown(index=False, disable_numparse=True))
                lines.append("")
        except Exception as e:
            lines.append(f"**ERROR executing query:** `{e}`\n")

        lines.append("---\n")

    output_md.parent.mkdir(parents=True, exist_ok=True)
    output_md.write_text("\n".join(lines), encoding="utf-8")
    conn.close()
    print(f"Executed {len(queries)} queries. Report written to {output_md}")


if __name__ == "__main__":
    main()
